# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: sandwich.proto

from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='sandwich.proto',
  package='sandwich',
  syntax='proto3',
  serialized_options=b'\n\023edu.cmu.cs.sandwichB\006Protos',
  create_key=_descriptor._internal_create_key,
  serialized_pb=b'\n\x0esandwich.proto\x12\x08sandwich\"\x8d\x01\n\x08ToServer\x12\r\n\x05width\x18\x01 \x01(\x05\x12\x0e\n\x06height\x18\x02 \x01(\x05\x12\x32\n\x0bzoom_status\x18\x03 \x01(\x0e\x32\x1d.sandwich.ToServer.ZoomStatus\".\n\nZoomStatus\x12\x0b\n\x07NO_CALL\x10\x00\x12\t\n\x05START\x10\x01\x12\x08\n\x04STOP\x10\x02\"a\n\x08ToClient\x12\x0f\n\x07\x61pp_key\x18\x01 \x01(\t\x12\x12\n\napp_secret\x18\x02 \x01(\t\x12\x16\n\x0emeeting_number\x18\x03 \x01(\t\x12\x18\n\x10meeting_password\x18\x04 \x01(\tB\x1d\n\x13\x65\x64u.cmu.cs.sandwichB\x06Protosb\x06proto3'
)



_TOSERVER_ZOOMSTATUS = _descriptor.EnumDescriptor(
  name='ZoomStatus',
  full_name='sandwich.ToServer.ZoomStatus',
  filename=None,
  file=DESCRIPTOR,
  create_key=_descriptor._internal_create_key,
  values=[
    _descriptor.EnumValueDescriptor(
      name='NO_CALL', index=0, number=0,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
    _descriptor.EnumValueDescriptor(
      name='START', index=1, number=1,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
    _descriptor.EnumValueDescriptor(
      name='STOP', index=2, number=2,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
  ],
  containing_type=None,
  serialized_options=None,
  serialized_start=124,
  serialized_end=170,
)
_sym_db.RegisterEnumDescriptor(_TOSERVER_ZOOMSTATUS)


_TOSERVER = _descriptor.Descriptor(
  name='ToServer',
  full_name='sandwich.ToServer',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='width', full_name='sandwich.ToServer.width', index=0,
      number=1, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='height', full_name='sandwich.ToServer.height', index=1,
      number=2, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='zoom_status', full_name='sandwich.ToServer.zoom_status', index=2,
      number=3, type=14, cpp_type=8, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
    _TOSERVER_ZOOMSTATUS,
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=29,
  serialized_end=170,
)


_TOCLIENT = _descriptor.Descriptor(
  name='ToClient',
  full_name='sandwich.ToClient',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='app_key', full_name='sandwich.ToClient.app_key', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='app_secret', full_name='sandwich.ToClient.app_secret', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='meeting_number', full_name='sandwich.ToClient.meeting_number', index=2,
      number=3, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='meeting_password', full_name='sandwich.ToClient.meeting_password', index=3,
      number=4, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=172,
  serialized_end=269,
)

_TOSERVER.fields_by_name['zoom_status'].enum_type = _TOSERVER_ZOOMSTATUS
_TOSERVER_ZOOMSTATUS.containing_type = _TOSERVER
DESCRIPTOR.message_types_by_name['ToServer'] = _TOSERVER
DESCRIPTOR.message_types_by_name['ToClient'] = _TOCLIENT
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

ToServer = _reflection.GeneratedProtocolMessageType('ToServer', (_message.Message,), {
  'DESCRIPTOR' : _TOSERVER,
  '__module__' : 'sandwich_pb2'
  # @@protoc_insertion_point(class_scope:sandwich.ToServer)
  })
_sym_db.RegisterMessage(ToServer)

ToClient = _reflection.GeneratedProtocolMessageType('ToClient', (_message.Message,), {
  'DESCRIPTOR' : _TOCLIENT,
  '__module__' : 'sandwich_pb2'
  # @@protoc_insertion_point(class_scope:sandwich.ToClient)
  })
_sym_db.RegisterMessage(ToClient)


DESCRIPTOR._options = None
# @@protoc_insertion_point(module_scope)
